enum AppApi {
  LOGIN,
  SIGNUP,
  OTP,
  GETUSER,
  GETALLCONNECTIONS,
  GETALLPENDINGCONNECTIONS,
  SENDCONNECTIONREQUEST,
  GETALLUSERS,
  CHAT,
  NONE
}

enum Gender { MALE, FEMALE, OTHER, UNIDENTIFIED }

enum ProviderType { GOOGLE, FB, APPLE, NORMAL }

enum DeviceType { ANDROID, IPHONE, ANY }
